name: SonarCloud Debug Workflow

on:
  push:
    branches:
      - '**'

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: cae8d160e9f72cbf43555f50861dd377cd964e7f

      - name: Debug Quality Gate Status
        run: |
          echo "Fetching SonarCloud Quality Gate Status..."
          RESPONSE=$(curl -s -u "cae8d160e9f72cbf43555f50861dd377cd964e7f:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Deb-sudo_python")
          echo "SonarCloud Response: $RESPONSE"
          STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $STATUS"
          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed with status: $STATUS"
            exit 1
          fi

